version: '3.3'

services:
   db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: deskreeStudio
       MYSQL_USER: deskreeStudio
       MYSQL_PASSWORD: deskreeStudio

   app:
     build: .
     command: php artisan serve --host=0.0.0.0
     ports:
       - "8000:8000"
     restart: always
     volumes:
       - "./:/usr/src/app"
     depends_on:
       - db
